import React from 'react'

export default function CountryPFSelect({ pais, setPais, setContinente, continente, errorFields }) {

    // Mapeo de países a continentes
    const countryToContinent = {
        "Afghanistan": "Asia",
        "Åland (Finland)": "Europe",
        "Albania": "Europe",
        "Algeria": "Africa",
        "American Samoa (US)": "Oceania",
        "Andorra": "Europe",
        "Angola": "Africa",
        "Anguilla (BOT)": "North America",
        "Antigua and Barbuda": "North America",
        "Argentina": "South America",
        "Armenia": "Asia",
        "Artsakh": "Asia",
        "Aruba (Netherlands)": "North America",
        "Australia": "Oceania",
        "Austria": "Europe",
        "Azerbaijan": "Asia",
        "Bahamas": "North America",
        "Bahrain": "Asia",
        "Bangladesh": "Asia",
        "Barbados": "North America",
        "Belarus": "Europe",
        "Belgium": "Europe",
        "Belize": "Central America",
        "Benin": "Africa",
        "Bermuda (BOT)": "North America",
        "Bhutan": "Asia",
        "Bolivia": "South America",
        "Bonaire (Netherlands)": "North America",
        "Bosnia and Herzegovina": "Europe",
        "Botswana": "Africa",
        "Brazil": "South America",
        "British Virgin Islands (BOT)": "North America",
        "Brunei": "Asia",
        "Bulgaria": "Europe",
        "Burkina Faso": "Africa",
        "Burundi": "Africa",
        "Cambodia": "Asia",
        "Cameroon": "Africa",
        "Canada": "North America",
        "Cape Verde": "Africa",
        "Cayman Islands (BOT)": "North America",
        "Central African Republic": "Africa",
        "Chad": "Africa",
        "Chile": "South America",
        "China": "Asia",
        "Christmas Island (Australia)": "Oceania",
        "Cocos (Keeling) Islands (Australia)": "Oceania",
        "Colombia": "South America",
        "Comoros": "Africa",
        "Congo": "Africa",
        "Cook Islands": "Oceania",
        "Costa Rica": "Central America",
        "Croatia": "Europe",
        "Cuba": "North America",
        "Curaçao (Netherlands)": "North America",
        "Cyprus": "Asia",
        "Czech Republic": "Europe",
        "Denmark": "Europe",
        "Djibouti": "Africa",
        "Dominica": "North America",
        "Dominican Republic": "North America",
        "DR Congo": "Africa",
        "East Timor": "Asia",
        "Ecuador": "South America",
        "Egypt": "Africa",
        "El Salvador": "North America",
        "Equatorial Guinea": "Africa",
        "Eritrea": "Africa",
        "Estonia": "Europe",
        "Eswatini": "Africa",
        "Ethiopia": "Africa",
        "Falkland Islands (BOT)": "South America",
        "Faroe Islands (Denmark)": "Europe",
        "Fiji": "Oceania",
        "Finland": "Europe",
        "France": "Europe",
        "French Guiana (France)": "South America",
        "French Polynesia (France)": "Oceania",
        "Gabon": "Africa",
        "Gambia": "Africa",
        "Georgia": "Asia",
        "Germany": "Europe",
        "Ghana": "Africa",
        "Gibraltar (BOT)": "Europe",
        "Greece": "Europe",
        "Greenland (Denmark)": "North America",
        "Grenada": "North America",
        "Guadeloupe (France)": "North America",
        "Guam (US)": "Oceania",
        "Guatemala": "Central America",
        "Guernsey (Crown Dependency)": "Europe",
        "Guinea": "Africa",
        "Guinea-Bissau": "Africa",
        "Guyana": "South America",
        "Haiti": "North America",
        "Honduras": "Central America",
        "Hong Kong": "Asia",
        "Hungary": "Europe",
        "Iceland": "Europe",
        "India": "Asia",
        "Indonesia": "Asia",
        "Iran": "Asia",
        "Iraq": "Asia",
        "Ireland": "Europe",
        "Isle of Man (Crown Dependency)": "Europe",
        "Israel": "Asia",
        "Italy": "Europe",
        "Ivory Coast": "Africa",
        "Jamaica": "North America",
        "Japan": "Asia",
        "Jersey (Crown Dependency)": "Europe",
        "Jordan": "Asia",
        "Kazakhstan": "Asia",
        "Kenya": "Africa",
        "Kiribati": "Oceania",
        "Kosovo": "Europe",
        "Kuwait": "Asia",
        "Kyrgyzstan": "Asia",
        "Laos": "Asia",
        "Latvia": "Europe",
        "Lebanon": "Asia",
        "Lesotho": "Africa",
        "Liberia": "Africa",
        "Libya": "Africa",
        "Liechtenstein": "Europe",
        "Lithuania": "Europe",
        "Luxembourg": "Europe",
        "Macau": "Asia",
        "Madagascar": "Africa",
        "Malawi": "Africa",
        "Malaysia": "Asia",
        "Maldives": "Asia",
        "Mali": "Africa",
        "Malta": "Europe",
        "Marshall Islands": "Oceania",
        "Martinique (France)": "North America",
        "Mauritania": "Africa",
        "Mauritius": "Africa",
        "Mayotte (France)": "Africa",
        "Mexico": "North America",
        "Micronesia": "Oceania",
        "Moldova": "Europe",
        "Monaco": "Europe",
        "Mongolia": "Asia",
        "Montenegro": "Europe",
        "Montserrat (BOT)": "North America",
        "Morocco": "Africa",
        "Mozambique": "Africa",
        "Myanmar": "Asia",
        "Namibia": "Africa",
        "Nauru": "Oceania",
        "Nepal": "Asia",
        "Netherlands": "Europe",
        "New Caledonia (France)": "Oceania",
        "New Zealand": "Oceania",
        "Nicaragua": "Central America",
        "Niger": "Africa",
        "Nigeria": "Africa",
        "Niue": "Oceania",
        "Norfolk Island (Australia)": "Oceania",
        "North Korea": "Asia",
        "North Macedonia": "Europe",
        "Northern Cyprus": "Asia",
        "Northern Mariana Islands (US)": "Oceania",
        "Norway": "Europe",
        "Oman": "Asia",
        "Pakistan": "Asia",
        "Palau": "Oceania",
        "Palestine": "Asia",
        "Panama": "Central America",
        "Papua New Guinea": "Oceania",
        "Paraguay": "South America",
        "Peru": "South America",
        "Philippines": "Asia",
        "Pitcairn Islands (BOT)": "Oceania",
        "Poland": "Europe",
        "Portugal": "Europe",
        "Puerto Rico (US)": "North America",
        "Qatar": "Asia",
        "Réunion (France)": "Africa",
        "Romania": "Europe",
        "Russia": "Europe",
        "Rwanda": "Africa",
        "Saba (Netherlands)": "North America",
        "Saint Barthélemy (France)": "North America",
        "Saint Helena, Ascension and Tristan da Cunha (BOT)": "Africa",
        "Saint Kitts and Nevis": "North America",
        "Saint Lucia": "North America",
        "Saint Martin (France)": "North America",
        "Saint Pierre and Miquelon (France)": "North America",
        "Saint Vincent and the Grenadines": "North America",
        "Samoa": "Oceania",
        "San Marino": "Europe",
        "São Tomé and Príncipe": "Africa",
        "Saudi Arabia": "Asia",
        "Senegal": "Africa",
        "Serbia": "Europe",
        "Seychelles": "Africa",
        "Sierra Leone": "Africa",
        "Singapore": "Asia",
        "Sint Eustatius (Netherlands)": "North America",
        "Sint Maarten (Netherlands)": "North America",
        "Slovakia": "Europe",
        "Slovenia": "Europe",
        "Solomon Islands": "Oceania",
        "Somalia": "Africa",
        "South Africa": "Africa",
        "South Korea": "Asia",
        "South Sudan": "Africa",
        "Spain": "Europe",
        "Sri Lanka": "Asia",
        "Sudan": "Africa",
        "Suriname": "South America",
        "Sweden": "Europe",
        "Switzerland": "Europe",
        "Syria": "Asia",
        "Taiwan": "Asia",
        "Tajikistan": "Asia",
        "Tanzania": "Africa",
        "Thailand": "Asia",
        "Togo": "Africa",
        "Tonga": "Oceania",
        "Trinidad and Tobago": "North America",
        "Tunisia": "Africa",
        "Turkey": "Asia",
        "Turkmenistan": "Asia",
        "Turks and Caicos Islands (BOT)": "North America",
        "Tuvalu": "Oceania",
        "Uganda": "Africa",
        "Ukraine": "Europe",
        "United Arab Emirates": "Asia",
        "United Kingdom": "Europe",
        "United States": "North America",
        "Uruguay": "South America",
        "Uzbekistan": "Asia",
        "Vanuatu": "Oceania",
        "Vatican City": "Europe",
        "Venezuela": "South America",
        "Vietnam": "Asia",
        "Wallis and Futuna (France)": "Oceania",
        "Western Sahara": "Africa",
        "Yemen": "Asia",
        "Zambia": "Africa",
        "Zimbabwe": "Africa"
    };

    const handleCountryChange = (e) => {
        const country = e.target.value;
        setPais(country);
        setContinente(countryToContinent[country] || "");
    };


    return (
        <div>
            <div>
                <label className='text-gray-400'>Host Country *</label>
                <select
                    className={errorFields.pais ? "input-error" : "border border-gray-200 bg-zinc-100/40"}
                    value={pais}
                    
                    onChange={handleCountryChange}>
                    <option value="">Select a country</option>
                    {Object.keys(countryToContinent).map(country => (
                        <option key={country} value={country}>{country}</option>
                    ))}
                </select>
            </div>
            <div>
                <label className='text-gray-400' >Continent </label>
                <input type="text" value={continente} readOnly />
            </div>
        </div>
    )
}
